apiVersion: v1
kind: Service
metadata:
  name: node-prom-svc
  labels:
    app: node-prom
spec:
  type: NodePort
  selector:
    app: node-prom
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081   # this NodePort for application here node.js, so shoudn't be conflict with grafana nodeport

